# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/intel/labs/open62541

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/intel/labs/open62541/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/intel/labs/open62541/build/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/intel/labs/open62541/build/CMakeFiles /home/intel/labs/open62541/build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/intel/labs/open62541/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named open62541-amalgamation-source

# Build rule for target.
open62541-amalgamation-source: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 open62541-amalgamation-source
.PHONY : open62541-amalgamation-source

# fast build rule for target.
open62541-amalgamation-source/fast:
	$(MAKE) -f CMakeFiles/open62541-amalgamation-source.dir/build.make CMakeFiles/open62541-amalgamation-source.dir/build
.PHONY : open62541-amalgamation-source/fast

#=============================================================================
# Target rules for targets named open62541-generator-statuscode

# Build rule for target.
open62541-generator-statuscode: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 open62541-generator-statuscode
.PHONY : open62541-generator-statuscode

# fast build rule for target.
open62541-generator-statuscode/fast:
	$(MAKE) -f CMakeFiles/open62541-generator-statuscode.dir/build.make CMakeFiles/open62541-generator-statuscode.dir/build
.PHONY : open62541-generator-statuscode/fast

#=============================================================================
# Target rules for targets named open62541-generator-types

# Build rule for target.
open62541-generator-types: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 open62541-generator-types
.PHONY : open62541-generator-types

# fast build rule for target.
open62541-generator-types/fast:
	$(MAKE) -f CMakeFiles/open62541-generator-types.dir/build.make CMakeFiles/open62541-generator-types.dir/build
.PHONY : open62541-generator-types/fast

#=============================================================================
# Target rules for targets named cpplint

# Build rule for target.
cpplint: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cpplint
.PHONY : cpplint

# fast build rule for target.
cpplint/fast:
	$(MAKE) -f CMakeFiles/cpplint.dir/build.make CMakeFiles/cpplint.dir/build
.PHONY : cpplint/fast

#=============================================================================
# Target rules for targets named open62541-generator-transport

# Build rule for target.
open62541-generator-transport: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 open62541-generator-transport
.PHONY : open62541-generator-transport

# fast build rule for target.
open62541-generator-transport/fast:
	$(MAKE) -f CMakeFiles/open62541-generator-transport.dir/build.make CMakeFiles/open62541-generator-transport.dir/build
.PHONY : open62541-generator-transport/fast

#=============================================================================
# Target rules for targets named lint

# Build rule for target.
lint: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lint
.PHONY : lint

# fast build rule for target.
lint/fast:
	$(MAKE) -f CMakeFiles/lint.dir/build.make CMakeFiles/lint.dir/build
.PHONY : lint/fast

#=============================================================================
# Target rules for targets named open62541-amalgamation-header

# Build rule for target.
open62541-amalgamation-header: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 open62541-amalgamation-header
.PHONY : open62541-amalgamation-header

# fast build rule for target.
open62541-amalgamation-header/fast:
	$(MAKE) -f CMakeFiles/open62541-amalgamation-header.dir/build.make CMakeFiles/open62541-amalgamation-header.dir/build
.PHONY : open62541-amalgamation-header/fast

#=============================================================================
# Target rules for targets named open62541-generator-namespace

# Build rule for target.
open62541-generator-namespace: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 open62541-generator-namespace
.PHONY : open62541-generator-namespace

# fast build rule for target.
open62541-generator-namespace/fast:
	$(MAKE) -f CMakeFiles/open62541-generator-namespace.dir/build.make CMakeFiles/open62541-generator-namespace.dir/build
.PHONY : open62541-generator-namespace/fast

#=============================================================================
# Target rules for targets named open62541-object

# Build rule for target.
open62541-object: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 open62541-object
.PHONY : open62541-object

# fast build rule for target.
open62541-object/fast:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/build
.PHONY : open62541-object/fast

#=============================================================================
# Target rules for targets named open62541

# Build rule for target.
open62541: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 open62541
.PHONY : open62541

# fast build rule for target.
open62541/fast:
	$(MAKE) -f CMakeFiles/open62541.dir/build.make CMakeFiles/open62541.dir/build
.PHONY : open62541/fast

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) -f doc/CMakeFiles/doc.dir/build.make doc/CMakeFiles/doc.dir/build
.PHONY : doc/fast

#=============================================================================
# Target rules for targets named doc_pdf

# Build rule for target.
doc_pdf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc_pdf
.PHONY : doc_pdf

# fast build rule for target.
doc_pdf/fast:
	$(MAKE) -f doc/CMakeFiles/doc_pdf.dir/build.make doc/CMakeFiles/doc_pdf.dir/build
.PHONY : doc_pdf/fast

#=============================================================================
# Target rules for targets named doc_latex

# Build rule for target.
doc_latex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc_latex
.PHONY : doc_latex

# fast build rule for target.
doc_latex/fast:
	$(MAKE) -f doc/CMakeFiles/doc_latex.dir/build.make doc/CMakeFiles/doc_latex.dir/build
.PHONY : doc_latex/fast

open62541.o: open62541.c.o

.PHONY : open62541.o

# target to build an object file
open62541.c.o:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/open62541.c.o
.PHONY : open62541.c.o

open62541.i: open62541.c.i

.PHONY : open62541.i

# target to preprocess a source file
open62541.c.i:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/open62541.c.i
.PHONY : open62541.c.i

open62541.s: open62541.c.s

.PHONY : open62541.s

# target to generate assembly for a file
open62541.c.s:
	$(MAKE) -f CMakeFiles/open62541-object.dir/build.make CMakeFiles/open62541-object.dir/open62541.c.s
.PHONY : open62541.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... package"
	@echo "... install/local"
	@echo "... open62541-amalgamation-source"
	@echo "... open62541-generator-statuscode"
	@echo "... open62541-generator-types"
	@echo "... cpplint"
	@echo "... open62541-generator-transport"
	@echo "... lint"
	@echo "... install"
	@echo "... open62541-amalgamation-header"
	@echo "... open62541-generator-namespace"
	@echo "... list_install_components"
	@echo "... install/strip"
	@echo "... open62541-object"
	@echo "... open62541"
	@echo "... doc"
	@echo "... doc_pdf"
	@echo "... doc_latex"
	@echo "... open62541.o"
	@echo "... open62541.i"
	@echo "... open62541.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

